export default {
  MAIN_ROUTE: "MAIN_ROUTE",
  AUTHSCREEN: "AUTHSCREEN",
  TABNAVIGATOR: "TABNAVIGATOR",
  HOMENAVIGATOR: "HOMENAVIGATOR",
  HOMESCREEN: "HOMESCREEN",
  EVENTDETAILSSCREEN: "EVENTDETAILSSCREEN",
  PROFILESCREEN: "PROFILESCREEN",
  FAVORITESCREEN: "FAVORITESCREEN",
  PURCHASE_TICKET_SCREEN: "PURCHASE_TICKET_SCREEN",
};
